import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="flex h-screen">
      {/* Sidebar */}
      <nav className="w-64 bg-gray-800 text-white p-4 h-full fixed">
        <h2 className="text-xl font-bold mb-4">Shona Lang Docs</h2>
        <ul>
          <li className="mb-2">
            <Link href="/" className="block p-2 hover:bg-gray-700">
              Home
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/installation" className="block p-2 hover:bg-gray-700">
              Installation
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/syntax" className="block p-2 hover:bg-gray-700">
              Syntax Guide
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/variables" className="block p-2 hover:bg-gray-700">
              Variables
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/functions" className="block p-2 hover:bg-gray-700">
              Functions
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/file-handling" className="block p-2 hover:bg-gray-700">
              File Handling
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/running-code" className="block p-2 hover:bg-gray-700">
              Running Code
            </Link>
          </li>
        </ul>
      </nav>
      <div className="ml-64 p-6 flex-1">{children}</div>
    </div>
      </body>
    </html>
  );
}
